name: neural_nexus
description: "A new heath app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  fluttertoast: ^8.2.2
  video_player: ^2.7.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/homepage_bg.jpg